# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

branches:
  only:
    - master
language: objective-c
osx_image: xcode8.3
env:
  matrix:
    - OS='10.1' name='iPhone 6'

# cache: cocoapods
podfile: Example/Podfile
before_install:
# - gem install xcpretty
- gem install cocoapods # Since Travis is not always on latest version
- pod install --verbose --project-directory=Example
script:
- xcodebuild clean -workspace Example/GFCoreDataSource.xcworkspace -scheme GFCoreDataSource-Example
- xcodebuild -destination "platform=iOS Simulator,OS=10.1,name=iPhone 6" -workspace Example/GFCoreDataSource.xcworkspace -scheme GFCoreDataSource-Example -sdk iphonesimulator10.1 ONLY_ACTIVE_ARCH=NO
- pod lib lint GFCoreDataSource.podspec
